name: 🐳 Build Docker images

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v4
      - 
        name: Get version
        id: version
        uses: nowsprinting/check-version-format-action@v3
        with:
          prefix: 'v'
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ssh:latest, ${{ secrets.DOCKERHUB_USERNAME }}/ssh:${{steps.version.outputs.major_without_prefix}}.${{steps.version.outputs.minor}}.${{steps.version.outputs.patch}}, ${{ secrets.DOCKERHUB_USERNAME }}/ssh:${{steps.version.outputs.major_without_prefix}}.${{steps.version.outputs.minor}}, ${{ secrets.DOCKERHUB_USERNAME }}/ssh:${{steps.version.outputs.major_without_prefix}}
